MY FIRST NOTEBOOK

In [ ]:
print("hello!")

In [1]:
import pandas as pd

NUMPY: ARRAYS

In [2]:
import numpy as np

In [ ]:
a = np.array([2,4,6,8])

In [ ]:
a
a.dtype

MATRIX: DIMENSIONAL ARRAYS

In [ ]:
c = np.array([
    [
    [2,4,6],
    [1,2,3],
],
[
    [4,2,4],
    [5,6,7],
]
    ])
c

In [ ]:
c.shape

PERFORMING SUMMARY STATISTICS ON MATRICES

In [ ]:
#c.sum()
c.mean()

BOOLEAN ARRAYS

In [ ]:
a

In [ ]:
a >=2

In [ ]:
a.mean()

In [ ]:
a[a<a.mean()]

LOADING DATA FROM FILE WITH NUMPY

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
print(filedata)

PANDAS

In [2]:
import pandas as pd

PANDAS SERIES

In [ ]:
#creating a pandas series
g7_pop = pd.Series([35.467, 63.951, 80.94, 60.665, 127.061, 64.511, 318.523])
g7_pop
#giving it a name
g7_pop.name = "G7 population in millions"
g7_pop
#indexing
g7_pop.index = ['Canada', 'France', 'Germany', 'Italy', 'Japan', 'United Kingdom', 'United States']
g7_pop

In [ ]:
#summary statistics
g7_pop.describe()

In [ ]:
#This can be useful for identifying outliers or values that are not close to the average.
g7_pop[(g7_pop >g7_pop.mean() - g7_pop.std() / 2) | (g7_pop > g7_pop.mean() + g7_pop.std() / 2)]

In [ ]:
#masking
#g7_pop <=60
g7_pop[g7_pop <=60]

DATAFRAME

In [4]:
import matplotlib.pyplot as plt

In [ ]:
#create a data frame showing the atudents scores
exam_score = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Julia'],
    'Age': [23, 35, 45, 28, 32, 40, 29, 31, 38, 27],
    'Country': ['USA', 'Canada', 'UK', 'USA', 'Germany', 'France', 'Canada', 'UK', 'Germany', 'France'],
    'Score': [88, 92, 79, 85, 90, 87, 95, 80, 84, 91],
    'test1': [18, 17, 15, 19, 16, 20, 14, 13, 18, 17],
    'test2': [16, 19, 18, 17, 15, 20, 13, 14, 19, 16]
})
exam_score
#Add index names to the dataframe using the 'Name' column
exam_score.index = exam_score['Name']
exam_score
#drop the name column
exam_score = exam_score.drop('Name', axis=1)
exam_score

In [27]:
exam_score['Average'] = (exam_score['Score'] * 0.6) + (exam_score['test1'] * 0.2) + (exam_score['test2'] * 0.2)
exam_score

         Age  Country  Score  test1  test2  Average
Name
Alice     23      USA     88     18     16     59.6
Bob       35   Canada     92     17     19     62.4
Charlie   45       UK     79     15     18     54.0
David     28      USA     85     19     17     58.2
Eva       32  Germany     90     16     15     60.2
Frank     40   France     87     20     20     60.2
Grace     29   Canada     95     14     13     62.4
Helen     31       UK     80     13     14     53.4
Ian       38  Germany     84     18     19     57.8
Julia     27   France     91     17     16     61.2

READING CSV FILES

In [ ]:
#i had to move the folder and make it a sub folder in the working directory i.e jupyter notebook folder
#read a csv file
bitcoin = pd.read_csv('PRACTICE DATASETS/btc-market-price.csv', header=None)
#set column names
bitcoin.columns = ['Timestamp', 'Price']
#convert the timestamp to a datetime object and set it as the index
bitcoin['Timestamp'] = pd.to_datetime(bitcoin['Timestamp'])
bitcoin.set_index('Timestamp', inplace=True)
bitcoin

                  Price
Timestamp
2017-04-02  1099.169125
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937
...                 ...
2018-03-28  7960.380000
2018-03-29  7172.280000
2018-03-30  6882.531667
2018-03-31  6935.480000
2018-04-01  6794.105000

[365 rows x 1 columns]

In [ ]:
#gives the value at a particular date/row
bitcoin.loc['18/04/2017 00:00']

Price    1216.186743
Name: 2017-04-18 00:00:00, dtype: float64

In [ ]:
#gives you the first 10 rows
bitcoin.head(10)

                  Price
Timestamp
2017-04-02  1099.169125
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937
2017-04-07  1190.454250
2017-04-08  1181.149838
2017-04-09  1208.800500
2017-04-10  1207.744875
2017-04-11  1226.617037

In [35]:
#check the current working directory
import os
print(os.getcwd())

c:\Users\Praise\Desktop\jupy notebook

In [37]:
# In a notebook cell
!pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.66-py2.py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: requests>=2.31 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2.32.5)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.12.tar.gz (19 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (4.4.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (2025.2)
Collecting frozendict>=2.3.4 (from yfinance)
  Downloading frozendict-2.4.6-py313-none-any.whl.metadata (23 kB)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.2.tar.gz (949 kB)
     ---------------------------------------- 0.0/949.2 kB ? eta -:--:--
     ---------------------------------------- 0.0/949.2 kB ? eta -:--:--
     ---------------------------------------- 0.0/949.2 kB ? eta -:--:--
     ----------- ---------------------------- 262.1/949.2 kB ? eta -:--:--
     ----------- ---------------------------- 262.1/949.2 kB ? eta -:--:--
     ----------- ---------------------------- 262.1/949.2 kB ? eta -:--:--
     ----------- ---------------------------- 262.1/949.2 kB ? eta -:--:--
     ------------------- ---------------- 524.3/949.2 kB 328.4 kB/s eta 0:00:02
     ----------------------------- ------ 786.4/949.2 kB 448.4 kB/s eta 0:00:01
     --------------------------------------- 949.2/949.2 kB 515.5 kB/s  0:00:01
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from yfinance) (4.13.5)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.13.0-cp39-abi3-win_amd64.whl.metadata (13 kB)
Collecting protobuf>=3.19.0 (from yfinance)
  Downloading protobuf-6.32.1-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp313-cp313-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.8.3)
Requirement already satisfied: pycparser in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->yfinance) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\praise\appdata\local\programs\python\python313\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)
Downloading yfinance-0.2.66-py2.py3-none-any.whl (123 kB)
Downloading curl_cffi-0.13.0-cp39-abi3-win_amd64.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------ --------------------------- 0.5/1.6 MB 465.1 kB/s eta 0:00:03
   ------------ --------------------------- 0.5/1.6 MB 465.1 kB/s eta 0:00:03
   ------------------- -------------------- 0.8/1.6 MB 522.0 kB/s eta 0:00:02
   ------------------------- -------------- 1.0/1.6 MB 647.4 kB/s eta 0:00:01
   ------------------------- -------------- 1.0/1.6 MB 647.4 kB/s eta 0:00:01
   ------------------------- -------------- 1.0/1.6 MB 647.4 kB/s eta 0:00:01
   -------------------------------- ------- 1.3/1.6 MB 604.7 kB/s eta 0:00:01
   -------------------------------- ------- 1.3/1.6 MB 604.7 kB/s eta 0:00:01
   -------------------------------------- - 1.6/1.6 MB 581.4 kB/s eta 0:00:01
   -------------------------------------- - 1.6/1.6 MB 581.4 kB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 509.3 kB/s  0:00:02
Downloading frozendict-2.4.6-py313-none-any.whl (16 kB)
Downloading protobuf-6.32.1-cp310-abi3-win_amd64.whl (435 kB)
Downloading websockets-15.0.1-cp313-cp313-win_amd64.whl (176 kB)
Building wheels for collected packages: multitasking, peewee
  Building wheel for multitasking (pyproject.toml): started
  Building wheel for multitasking (pyproject.toml): finished with status 'done'
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15703 sha256=5046742fcba03843dd994503f9c79c03d285d904b6fe356d57cf950addd92b5a
  Stored in directory: c:\users\praise\appdata\local\pip\cache\wheels\1e\df\0f\e2bbb22d689b30c681feb5410ab64a2523437b34c8ecfc6476
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.18.2-py3-none-any.whl size=139153 sha256=0adae0c8ac87261e7d3f1092c999e41ee49d9206dc2583885e94438a26e973fb
  Stored in directory: c:\users\praise\appdata\local\pip\cache\wheels\1c\48\cc\00b7d0e7defa21a58915654917c89eaedd32a6e614d8e4ad92
Successfully built multitasking peewee
Installing collected packages: peewee, multitasking, websockets, protobuf, frozendict, curl_cffi, yfinance

   ---------------------------------------- 0/7 [peewee]
   ---------------------------------------- 0/7 [peewee]
   ---------------------------------------- 0/7 [peewee]
   ---------------------------------------- 0/7 [peewee]
   ---------------------------------------- 0/7 [peewee]
   ---------------------------------------- 0/7 [peewee]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------- ---------------------------- 2/7 [websockets]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ----------------- ---------------------- 3/7 [protobuf]
   ---------------------- ----------------- 4/7 [frozendict]
   ---------------------- ----------------- 4/7 [frozendict]
   ---------------------------- ----------- 5/7 [curl_cffi]
   ---------------------------- ----------- 5/7 [curl_cffi]
   ---------------------------- ----------- 5/7 [curl_cffi]
   ---------------------------- ----------- 5/7 [curl_cffi]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------- ----- 6/7 [yfinance]
   ---------------------------------------- 7/7 [yfinance]

Successfully installed curl_cffi-0.13.0 frozendict-2.4.6 multitasking-0.0.12 peewee-3.18.2 protobuf-6.32.1 websockets-15.0.1 yfinance-0.2.66

In [7]:
import yfinance as yf

# Fetch Apple stock data for the last 10 years
apple = yf.download("AAPL", start="2015-01-01", end="2025-01-01")

# Check it out
print(apple.head())

C:\Users\Praise\AppData\Local\Temp\ipykernel_8660\89175575.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  apple = yf.download("AAPL", start="2015-01-01", end="2025-01-01")
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AAPL']: SSLError('Failed to perform, curl: (35) Recv failure: Connection was reset. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')

Empty DataFrame
Columns: [(Adj Close, AAPL), (Close, AAPL), (High, AAPL), (Low, AAPL), (Open, AAPL), (Volume, AAPL)]
Index: []

In [8]:
apple.shape

(0, 6)

In [9]:
apple.describe()

Price  Adj Close Close High  Low Open Volume
Ticker      AAPL  AAPL AAPL AAPL AAPL   AAPL
count        0.0   0.0  0.0  0.0  0.0    0.0
mean         NaN   NaN  NaN  NaN  NaN    NaN
std          NaN   NaN  NaN  NaN  NaN    NaN
min          NaN   NaN  NaN  NaN  NaN    NaN
25%          NaN   NaN  NaN  NaN  NaN    NaN
50%          NaN   NaN  NaN  NaN  NaN    NaN
75%          NaN   NaN  NaN  NaN  NaN    NaN
max          NaN   NaN  NaN  NaN  NaN    NaN

In [10]:
apple.isnull()

Empty DataFrame
Columns: [(Adj Close, AAPL), (Close, AAPL), (High, AAPL), (Low, AAPL), (Open, AAPL), (Volume, AAPL)]
Index: []